name: Release ASDF on Tag

on:
  push:
    tags:
      - "v*" # Trigger only for tags starting with "v" followed by semantic version (e.g., v1.0.0)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip ASDF folder
        run: zip -r "asdf-${{ github.ref_name }}.zip" asdf

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: asdf-${{ github.ref_name }}.zip
          artifactContentType: application/zip
#          generateReleaseNotes: true
          draft: false
          prerelease: true
          artifactErrorsFailBuild: true
