# .github/workflows/release-czyz-folder.yml
name: Release ASDF on Tag

on:
  push:
    tags:
      - "v*" # Trigger only for tags starting with "v" followed by semantic version (e.g., v1.0.0)
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip ASDF folder
        run: zip -r "asdf-${{ github.ref_name }}.zip" asdf

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: true

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./asdf-${{ github.ref_name }}.zip
          asset_name: asdf-${{ github.ref_name }}.zip
          asset_content_type: application/zip
